version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
    - location: scripts/healthCheck.sh
      timeout: 60
      runas: root
