version: 0.0
os: linux
files:
  - source: target/smHDS-0.0.1-SNAPSHOT.war
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
