version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: codestar_remote_access
      timeout: 300
      runas: root
    - location: deploy.sh
      timeout: 300
      runas: root
    - location: healthCheck.sh
      timeout: 300
      runas: root
