version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
    - location: scripts/healthCheck.sh
      timeout: 300
      runas: root
