#!/bin/bash
cd /home/ec2-user/javaapp
#wget https://s3.amazonaws.com/dhqs-mirror-iad/apache-tomcat-8.0.39.tar.gz
#mkdir /opt/tomcat
#tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
#cd /opt/tomcat
#sed -i 's|port="8080"|port="80"|g' conf/server.xml
#rm -rf webapps/ROOT
#mv /home/ec2-user/javaapp/ROOT.war webapps/
#yum -y install java-1.8.0-openjdk-1.8.0.171
#alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java


#!/bin/bash
BUILD_PATH=$(ls /home/ec2-user/javaapp/*.war)
JAR_NAME=$(basename $BUILD_PATH)
echo "> build 파일명: $JAR_NAME"

echo "> build 파일 복사"
DEPLOY_PATH=/home/ec2-user/deployapp/
cp $BUILD_PATH $DEPLOY_PATH

echo "> springboot-deploy.jar 교체"
CP_JAR_PATH=$DEPLOY_PATH$JAR_NAME
APPLICATION_JAR_NAME=ROOT.war
APPLICATION_JAR=$DEPLOY_PATH$APPLICATION_JAR_NAME


ln -Tfs $CP_JAR_PATH $APPLICATION_JAR

echo "> 현재 실행중인 애플리케이션 pid 확인"
CURRENT_PID=$(pgrep -f $APPLICATION_JAR_NAME)

if [ -z $CURRENT_PID ]
then
  echo "> 현재 구동중인 애플리케이션이 없으므로 종료하지 않습니다."
else
  echo "> kill -15 $CURRENT_PID"
  kill -15 $CURRENT_PID
  sleep 5
fi

echo "> $APPLICATION_JAR 배포"
nohup java -jar $APPLICATION_JAR